# Generated by Django 3.2.25 on 2025-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App1', '0002_alter_items_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
