# Generated by Django 3.2.25 on 2025-05-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App1', '0003_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Booking_date',
            new_name='Booking_data',
        ),
    ]
